export interface CumulativeRewardTier {
  amount: number
  rewards: string[]
}

export const cumulativeRewards: CumulativeRewardTier[] = [
  {
    amount: 10,
    rewards: [
      'Morion (Bound) 200',
      'Gold Chest (Bound) 500',
      'Sunset\'s Mount Summon Style x11 (Bound) 20',
      'Sunset\'s Weapon Summon Style x11 (Bound) 20',
      '[L] Weapon Style Challenge Ticket (Bound) 1',
      '[L] Mount Summon Challenge Ticket (Bound) 1',
    ],
  },
  {
    amount: 50,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×50',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×50',
      '[L] Weapon Style Challenge Ticket (Bound) ×3',
      '[L] Mount Summon Challenge Ticket  (Bound) ×3',
      'Pupil Aircraft Toolbox (Bound) ×25',
      'Artisan\'s Aircaft Toolbox (Bound) ×5',
      'NightCrow Claw Talisman Chest (Bound) ×50',
      'Night Crow Beak Circlet Chest (Bound) ×50',
      'Night Crow Flight Feather Jewel Chest (Bound) ×50',
      'Night Crow Feather Brooch Chest  (Bound) ×50',
      'Night Hawk Mask Chest (Bound) ×50',
      'Night Hawk TailFeather Whistle Box (Bound) ×50',
      'Morion (Bound) ×500',
      'Gold Chest (Bound) x2500',
    ],
  },
  {
    amount: 100,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×100',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×100',
      '[L] Weapon Style Challenge Ticket (Bound) ×7',
      '[L] Mount Summon Challenge Ticket  (Bound) ×7',
      'Pupil Aircraft Toolbox (Bound) ×50',
      'Artisan\'s Aircaft Toolbox (Bound) ×10',
      'NightCrow Claw Talisman Chest (Bound) ×100',
      'Night Crow Beak Circlet Chest (Bound) ×100',
      'Night Crow Flight Feather Jewel Chest (Bound) ×100',
      'Night Crow Feather Brooch Chest  (Bound) ×100',
      'Night Hawk Mask Chest (Bound) ×100',
      'Night Hawk TailFeather Whistle Box (Bound) ×100',
      'Morion (Bound) ×1000',
      'Gold Chest (Bound) x5000',
    ],
  },
  {
    amount: 300,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×200',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×200',
      '[L] Weapon Style Challenge Ticket (Bound) ×20',
      '[L] Mount Summon Challenge Ticket  (Bound) ×20',
      'Pupil Aircraft Toolbox (Bound) ×100',
      'Artisan\'s Aircaft Toolbox (Bound) ×30',
      'NightCrow Claw Talisman Chest (Bound) ×200',
      'Night Crow Beak Circlet Chest (Bound) ×200',
      'Night Crow Flight Feather Jewel Chest (Bound) ×200',
      'Night Crow Feather Brooch Chest  (Bound) ×200',
      'Night Hawk Mask Chest (Bound) ×200',
      'Night Hawk TailFeather Whistle Box (Bound) ×200',
      'Hourglass of Desert (Bound) · +6 ×1',
      'Die of Scorching Heat (Bound) · +6 ×1',
      'Die of Oceans (Bound) · +6 ×1',
      'Die of Thunderbolts (Bound) · +6 ×1',
      'Morion (Bound) ×3000',
      'Gold Chest (Bound) ×10,000',
      'Element Extraction of Harmony (Bound) ×3000',
    ],
  },
  {
    amount: 500,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×300',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×300',
      '[L] Weapon Style Challenge Ticket (Bound) ×30',
      '[L] Mount Summon Challenge Ticket  (Bound) ×30',
      'Pupil Aircraft Toolbox (Bound) ×150',
      'Artisan\'s Aircaft Toolbox (Bound) ×50',
      'NightCrow Claw Talisman Chest (Bound) ×200',
      'Night Crow Beak Circlet Chest (Bound) ×200',
      'Night Crow Flight Feather Jewel Chest (Bound) ×200',
      'Night Crow Feather Brooch Chest  (Bound) ×200',
      'Night Hawk Mask Chest (Bound) ×200',
      'Night Hawk TailFeather Whistle Box (Bound) ×200',
      'Hourglass of Desert (Bound) · +6 ×1',
      'Die of Scorching Heat (Bound) · +6 ×1',
      'Die of Oceans (Bound) · +6 ×1',
      'Die of Thunderbolts (Bound) · +6 ×1',
      'Morion (Bound) ×3000',
      'Gold Chest (Bound) ×15,000',
      'Element Extraction of Harmony (Bound) ×5000',
    ],
  },
  {
    amount: 1000,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×500',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×500',
      '[L] Weapon Style Challenge Ticket (Bound) ×30',
      '[L] Mount Summon Challenge Ticket  (Bound) ×30',
      'Pupil Aircraft Toolbox (Bound) ×150',
      'Artisan\'s Aircaft Toolbox (Bound) ×50',
      'NightCrow Claw Talisman Chest (Bound) ×500',
      'Night Crow Beak Circlet Chest (Bound) ×500',
      'Night Crow Flight Feather Jewel Chest (Bound) ×500',
      'Night Crow Feather Brooch Chest  (Bound) ×500',
      'Night Hawk Mask Chest (Bound) ×500',
      'Night Hawk TailFeather Whistle Box (Bound) ×500',
      'Hourglass of Desert (Bound) · +7 ×1',
      'Die of Scorching Heat (Bound) · +7 ×1',
      'Die of Oceans (Bound) · +7 ×1',
      'Die of Thunderbolts (Bound) · +7 ×1',
      'Morion (Bound) ×5000',
      'Gold Chest (Bound) ×20000',
      'Element Extraction of Harmony (Bound) ×5000',
    ],
  },
  {
    amount: 1500,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×700',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×700',
      '[L] Weapon Style Challenge Ticket (Bound) ×70',
      '[L] Mount Summon Challenge Ticket  (Bound) ×70',
      'Pupil Aircraft Toolbox (Bound) ×300',
      'Artisan\'s Aircaft Toolbox (Bound) ×100',
      'NightCrow Claw Talisman Chest (Bound) ×700',
      'Night Crow Beak Circlet Chest (Bound) ×700',
      'Night Crow Flight Feather Jewel Chest (Bound) ×700',
      'Night Crow Feather Brooch Chest  (Bound) ×700',
      'Night Hawk Mask Chest (Bound) ×700',
      'Night Hawk TailFeather Whistle Box (Bound) ×700',
      'Hourglass of Desert (Bound) · +7 ×1',
      'Die of Scorching Heat (Bound) · +7 ×1',
      'Die of Oceans (Bound) · +7 ×1',
      'Die of Thunderbolts (Bound) · +7 ×1',
      'Morion (Bound) ×10,000',
      'Gold Chest (Bound) ×25000',
      'Element Extraction of Harmony (Bound) ×50000',
    ],
  },
  {
    amount: 2000,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×1000',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×1000',
      '[L] Weapon Style Challenge Ticket (Bound) ×70',
      '[L] Mount Summon Challenge Ticket  (Bound) ×70',
      'Pupil Aircraft Toolbox (Bound) ×450',
      'Artisan\'s Aircaft Toolbox (Bound) ×150',
      'NightCrow Claw Talisman Chest (Bound) ×1000',
      'Night Crow Beak Circlet Chest (Bound) ×1000',
      'Night Crow Flight Feather Jewel Chest (Bound) ×1000',
      'Night Crow Feather Brooch Chest  (Bound) ×1000',
      'Night Hawk Mask Chest (Bound) ×1000',
      'Night Hawk TailFeather Whistle Box (Bound) ×1000',
      'Hourglass of Desert (Bound) · +8 ×1',
      'Die of Scorching Heat (Bound) · +8 ×1',
      'Die of Oceans (Bound) · +8 ×1',
      'Die of Thunderbolts (Bound) · +8 ×1',
      'Morion (Bound) ×10,000',
      'Gold Chest (Bound) ×30,000',
      'Element Extraction of Harmony(Bound) ×100000',
    ],
  },
  {
    amount: 3000,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×1500',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×1500',
      '[L] Weapon Style Challenge Ticket (Bound) ×70',
      '[L] Mount Summon Challenge Ticket  (Bound) ×70',
      'Pupil Aircraft Toolbox (Bound) ×600',
      'Artisan\'s Aircaft Toolbox (Bound) ×200',
      'NightCrow Claw Talisman Chest (Bound) ×2000',
      'Night Crow Beak Circlet Chest (Bound) ×2000',
      'Night Crow Flight Feather Jewel Chest (Bound) ×2000',
      'Night Crow Feather Brooch Chest  (Bound) ×2000',
      'Night Hawk Mask Chest (Bound) ×2000',
      'Night Hawk TailFeather Whistle Box (Bound) ×2000',
      'Hourglass of Desert (Bound) · +9 ×1',
      'Die of Scorching Heat (Bound) · +9 ×1',
      'Die of Oceans (Bound) · +9 ×1',
      'Die of Thunderbolts (Bound) · +9 ×1',
      'Morion (Bound) ×10,000',
      'Gold Chest (Bound) ×50,000',
      'Glorious Albatross Wings (Bound) x1',
    ],
  },
  {
    amount: 5000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×10',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×1,000',
      'Wind Orb Chest (Bound) ×100',
      '[L] Weapon Style Challenge Ticket (Bound) ×70',
      '[L] Mount Summon Challenge Ticket  (Bound) ×70',
      'Master\'s Aircraft Toolbox (Bound) ×50',
      'Knight Jewel (Bound) · +9 ×1',
      'Fighter\'s Jewel (Bound) · +9 ×1',
      'Philosopher\'s  Jewel (Bound) · +9 ×1',
      'Holy Relic (Bound) · +9 ×1',
      'Amulet of Life Bound) · +9 ×1',
      'Element Extraction of Harmony (Bound) ×100000',
    ],
  },
  {
    amount: 6000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×10',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×1,000',
      'Wind Orb Chest (Bound) ×200',
      '[L] Weapon Style Challenge Ticket (Bound) ×150',
      '[L] Mount Summon Challenge Ticket  (Bound) ×150',
      'Master\'s Aircraft Toolbox (Bound) ×50',
      'Knight Jewel (Bound) · +10 ×1',
      'Fighter\'s Jewel (Bound) · +10 ×1',
      'Philosopher\'s  Jewel (Bound) · +10 ×1',
      'Holy Relic (Bound) · +10 ×1',
      'Amulet of Life Bound) · +10 ×1',
      'Element Extraction of Harmony (Bound) ×100000',
      'Hourglass of Desert (Bound) · +10 ×1',
      'Die of Scorching Heat (Bound) · +10 ×1',
      'Die of Oceans (Bound) · +10 ×1',
      'Die of Thunderbolts (Bound) · +10 ×1',
    ],
  },
  {
    amount: 7000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×10',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×1,000',
      'Wind Orb Chest (Bound) ×300',
      '[L] Weapon Style Challenge Ticket (Bound) ×200',
      'Artisan\'s Aircraft Toolbox (Bound) ×50',
      'Knight Jewel (Bound) · +10 ×1',
      'Fighter\'s Jewel (Bound) · +10 ×1',
      'Philosopher\'s  Jewel (Bound) · +10 ×1',
      'Holy Relic (Bound) · +10 ×1',
      'Amulet of Life Bound) · +10 ×1',
      'Glided Emperor Crow x1',
    ],
  },
  {
    amount: 8000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×100',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×1,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×1,000',
      'Briliant Weapon Refinement Stone (Bound) x300',
      'Briliant Armor Refinement Stone (Bound) x300',
      'Briliant Accessories Refinement Stone (Bound) x300',
      'Briliant Artifact Refinement Stone (Bound) x300',
      'Wind Orb Chest (Bound) ×500',
      '[L] Weapon Style Challenge Ticket (Bound) ×300',
      'Artisan\'s Aircraft Toolbox (Bound) ×100',
      'Hourglass of Desert (Bound) · +11 ×1',
      'Die of Scorching Heat (Bound) · +11 ×1',
      'Die of Oceans (Bound) · +11 ×1',
      'Die of Thunderbolts (Bound) · +11 ×1',
      'Element Extraction of Harmony (Bound) ×100000',
    ],
  },
  {
    amount: 10000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×100',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×2,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×2,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×2,000',
      'Wind Orb Chest (Bound) ×500',
      'Artisan\'s Aircraft Toolbox (Bound) ×100',
      'NightCrow Claw Talisman Chest (Bound) +10×1',
      'Night Crow Beak Circlet Chest (Bound) +10×1',
      'Night Crow Flight Feather Jewel Chest (Bound) +10×1',
      'Night Crow Feather Brooch Chest  (Bound) +10×1',
      'Night Hawk Mask Chest (Bound) +10×1',
      'Night Hawk TailFeather Whistle Box (Bound) +10×1',
      'Knight Jewel (Bound) · +11 ×1',
      'Fighter\'s Jewel (Bound) · +11 ×1',
      'Philosopher\'s  Jewel (Bound) · +11 ×1',
      'Holy Relic (Bound) · +11 ×1',
      'Amulet of Life Bound) · +11 ×1',
      'Element Extraction of Harmony (Bound) ×100000',
    ],
  },
  {
    amount: 12000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×100',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×2,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×2,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×2,000',
      'Wind Orb Chest (Bound) ×500',
      'Artisan\'s Aircraft Toolbox (Bound) ×100',
      'NightCrow Claw Talisman Chest (Bound) +10×1',
      'Night Crow Beak Circlet Chest (Bound) +10×1',
      'Night Crow Flight Feather Jewel Chest (Bound) +10×1',
      'Night Crow Feather Brooch Chest  (Bound) +10×1',
      'Night Hawk Mask Chest (Bound) +10×1',
      'Night Hawk TailFeather Whistle Box (Bound) +10×1',
      'Knight Jewel (Bound) · +11 ×1',
      'Fighter\'s Jewel (Bound) · +11 ×1',
      'Philosopher\'s  Jewel (Bound) · +11 ×1',
      'Holy Relic (Bound) · +11 ×1',
      'Amulet of Life Bound) · +11 ×1',
      'Element Extraction of Harmony (Bound) ×200000',
    ],
  },
  {
    amount: 15000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×300',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×3,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×3,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×3,000',
      'Briliant Weapon Refinement Stone (Bound) x500',
      'Briliant Armor Refinement Stone (Bound) x500',
      'Briliant Accessories Refinement Stone (Bound) x500',
      'Briliant Artifact Refinement Stone (Bound) x500',
      'Wind Orb Chest (Bound) ×2000',
      'Artisan\'s Aircraft Toolbox (Bound) ×300',
      'Hourglass of Desert (Bound) · +12 ×1',
      'Die of Scorching Heat (Bound) · +12 ×1',
      'Die of Oceans (Bound) · +12 ×1',
      'Die of Thunderbolts (Bound) · +12 ×1',
      'NightCrow Claw Talisman Chest (Bound) +10×1',
      'Night Crow Beak Circlet Chest (Bound) +10×1',
      'Night Crow Flight Feather Jewel Chest (Bound) +10×1',
      'Night Crow Feather Brooch Chest  (Bound) +10×1',
      'Night Hawk Mask Chest (Bound) +10×1',
      'Night Hawk TailFeather Whistle Box (Bound) +10×1',
      'Tiaraka of Flame (Attribution) x1',
    ],
  },
  {
    amount: 20000,
    rewards: [
      'Superior Arcane Scroll of Enlightenment Chest (Bound) ×1000',
      'Shining Weapon Enhancement Scroll Chest (Bound) ×5,000',
      'Shining Armor Enhancement Scroll Chest (Bound) ×5,000',
      'Shining Accessory Enhancement Scroll Chest  (Bound) ×5,000',
      'Wind Orb Chest (Bound) ×5000',
      'Artisan\'s Aircraft Toolbox (Bound) ×500',
      'NightCrow Claw Talisman Chest (Bound) +11×1',
      'Night Crow Beak Circlet Chest (Bound) +11×1',
      'Night Crow Flight Feather Jewel Chest (Bound) +11×1',
      'Night Crow Feather Brooch Chest  (Bound) +11×1',
      'Night Hawk Mask Chest (Bound) +11×1',
      'Night Hawk TailFeather Whistle Box (Bound) +11×1',
      'Knight Jewel (Bound) · +12 ×1',
      'Fighter\'s Jewel (Bound) · +12 ×1',
      'Philosopher\'s  Jewel (Bound) · +12 ×1',
      'Holy Relic (Bound) · +12 ×1',
      'Amulet of Life Bound) · +12 ×1',
      'Crusade Loot Chest x100',
      'Element Extraction of Harmony (Bound) ×500000',
      'Guardian\'s Scepter x300000',
    ],
  },
]
