export interface CumulativeRewardTier {
  amount: number
  rewards: string[]
}

export const cumulativeRewards: CumulativeRewardTier[] = [
  {
    amount: 10,
    rewards: [
      'Morion (Bound) 200',
      'Gold Chest (Bound) 500',
      'Sunset\'s Mount Summon Style x11 (Bound) 20',
      'Sunset\'s Weapon Summon Style x11 (Bound) 20',
      '[L] Weapon Style Challenge Ticket (Bound) 1',
      '[L] Mount Summon Challenge Ticket (Bound) 1',
    ],
  },

  {
    amount: 50,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×50',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×50',
      '[L] Weapon Style Challenge Ticket (Bound) ×3',
      '[L] Mount Summon Challenge Ticket  (Bound) ×3',
      'Pupil Aircraft Toolbox (Bound) ×25',
      'Artisan\'s Aircaft Toolbox (Bound) ×5',
      'NightCrow Claw Talisman Chest (Bound) ×50',
      'Night Crow Beak Circlet Chest (Bound) ×50',
      'Night Crow Flight Feather Jewel Chest (Bound) ×50',
      'Night Crow Feather Brooch Chest  (Bound) ×50',
      'Night Hawk Mask Chest (Bound) ×50',
      'Night Hawk TailFeather Whistle Box (Bound) ×50',
      'Morion (Bound) ×500',
      'Gold Chest (Bound) x2500',
    ],
  },

  {
    amount: 100,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×100',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×100',
      '[L] Weapon Style Challenge Ticket (Bound) ×7',
      '[L] Mount Summon Challenge Ticket  (Bound) ×7',
      'Pupil Aircraft Toolbox (Bound) ×50',
      'Artisan\'s Aircaft Toolbox (Bound) ×10',
      'NightCrow Claw Talisman Chest (Bound) ×100',
      'Night Crow Beak Circlet Chest (Bound) ×100',
      'Night Crow Flight Feather Jewel Chest (Bound) ×100',
      'Night Crow Feather Brooch Chest  (Bound) ×100',
      'Night Hawk Mask Chest (Bound) ×100',
      'Night Hawk TailFeather Whistle Box (Bound) ×100',
      'Morion (Bound) ×1000',
      'Gold Chest (Bound) x5000',
    ],
  },

  {
    amount: 300,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×200',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×200',
      '[L] Weapon Style Challenge Ticket (Bound) ×20',
      '[L] Mount Summon Challenge Ticket  (Bound) ×20',
      'Pupil Aircraft Toolbox (Bound) ×100',
      'Artisan\'s Aircaft Toolbox (Bound) ×30',
      'NightCrow Claw Talisman Chest (Bound) ×200',
      'Night Crow Beak Circlet Chest (Bound) ×200',
      'Night Crow Flight Feather Jewel Chest (Bound) ×200',
      'Night Crow Feather Brooch Chest  (Bound) ×200',
      'Night Hawk Mask Chest (Bound) ×200',
      'Night Hawk TailFeather Whistle Box (Bound) ×200',
      'Hourglass of Desert (Bound) · +6 ×1',
      'Die of Scorching Heat (Bound) · +6 ×1',
      'Die of Oceans (Bound) · +6 ×1',
      'Die of Thunderbolts (Bound) · +6 ×1',
      'Morion (Bound) ×3000',
      'Gold Chest (Bound) ×10,000',
      'Element Extraction of Harmony (Bound) ×3000',
    ],
  },

  {
    amount: 500,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×300',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×300',
      '[L] Weapon Style Challenge Ticket (Bound) ×30',
      '[L] Mount Summon Challenge Ticket  (Bound) ×30',
      'Pupil Aircraft Toolbox (Bound) ×150',
      'Artisan\'s Aircaft Toolbox (Bound) ×50',
      'NightCrow Claw Talisman Chest (Bound) ×200',
      'Night Crow Beak Circlet Chest (Bound) ×200',
      'Night Crow Flight Feather Jewel Chest (Bound) ×200',
      'Night Crow Feather Brooch Chest  (Bound) ×200',
      'Night Hawk Mask Chest (Bound) ×200',
      'Night Hawk TailFeather Whistle Box (Bound) ×200',
      'Hourglass of Desert (Bound) · +6 ×1',
      'Die of Scorching Heat (Bound) · +6 ×1',
      'Die of Oceans (Bound) · +6 ×1',
      'Die of Thunderbolts (Bound) · +6 ×1',
      'Morion (Bound) ×3000',
      'Gold Chest (Bound) ×15,000',
      'Element Extraction of Harmony (Bound) ×5000',
    ],
  },

  {
    amount: 1000,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×500',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×500',
      '[L] Weapon Style Challenge Ticket (Bound) ×30',
      '[L] Mount Summon Challenge Ticket  (Bound) ×30',
      'Pupil Aircraft Toolbox (Bound) ×150',
      'Artisan\'s Aircaft Toolbox (Bound) ×50',
      'NightCrow Claw Talisman Chest (Bound) ×500',
      'Night Crow Beak Circlet Chest (Bound) ×500',
      'Night Crow Flight Feather Jewel Chest (Bound) ×500',
      'Night Crow Feather Brooch Chest  (Bound) ×500',
      'Night Hawk Mask Chest (Bound) ×500',
      'Night Hawk TailFeather Whistle Box (Bound) ×500',
      'Hourglass of Desert (Bound) · +7 ×1',
      'Die of Scorching Heat (Bound) · +7 ×1',
      'Die of Oceans (Bound) · +7 ×1',
      'Die of Thunderbolts (Bound) · +7 ×1',
      'Morion (Bound) ×5000',
      'Gold Chest (Bound) ×20000',
      'Element Extraction of Harmony (Bound) ×5000',
    ],
  },

  {
    amount: 1500,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×700',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×700',
      '[L] Weapon Style Challenge Ticket (Bound) ×70',
      '[L] Mount Summon Challenge Ticket  (Bound) ×70',
      'Pupil Aircraft Toolbox (Bound) ×300',
      'Artisan\'s Aircaft Toolbox (Bound) ×100',
      'NightCrow Claw Talisman Chest (Bound) ×700',
      'Night Crow Beak Circlet Chest (Bound) ×700',
      'Night Crow Flight Feather Jewel Chest (Bound) ×700',
      'Night Crow Feather Brooch Chest  (Bound) ×700',
      'Night Hawk Mask Chest (Bound) ×700',
      'Night Hawk TailFeather Whistle Box (Bound) ×700',
      'Hourglass of Desert (Bound) · +7 ×1',
      'Die of Scorching Heat (Bound) · +7 ×1',
      'Die of Oceans (Bound) · +7 ×1',
      'Die of Thunderbolts (Bound) · +7 ×1',
      'Morion (Bound) ×10,000',
      'Gold Chest (Bound) ×25000',
      'Element Extraction of Harmony (Bound) ×50000',
    ],
  },

  {
    amount: 2000,
    rewards: [
      'Sunset\'s Mount Summon Style x11  (Bound) ×1000',
      'Sunset\'s Weapon Summon Style x11 (Bound) ×1000',
      '[L] Weapon Style Challenge Ticket (Bound) ×70',
      '[L] Mount Summon Challenge Ticket  (Bound) ×70',
      'Pupil Aircraft Toolbox (Bound) ×450',
      'Artisan\'s Aircaft Toolbox (Bound) ×150',
      'NightCrow Claw Talisman Chest (Bound) ×1000',
      'Night Crow Beak Circlet Chest (Bound) ×1000',
      'Night Crow Flight Feather Jewel Chest (Bound) ×1000',
      'Night Crow Feather Brooch Chest  (Bound) ×1000',
      'Night Hawk Mask Chest (Bound) ×1000',
      'Night Hawk TailFeather Whistle Box (Bound) ×1000',
      'Hourglass of Desert (Bound) · +8 ×1',
      'Die of Scorching Heat (Bound) · +8 ×1',
      'Die of Oceans (Bound) · +8 ×1',
      'Die of Thunderbolts (Bound) · +8 ×1',
      'Morion (Bound) ×10,000',
      'Gold Chest (Bound) ×30,000',
      'Element Extraction of Harmony(Bound) ×100000',
    ],
  },
  {
    amount: 3000,
    rewards: [
      "Mileage ×200000",
      "Seal of Advancement (Bound) ×50000",
      "Higher Seal of Advancement   (Bound) ×2500",
      "Artisan Aircraft Toolbox   (Bound) ×400",
      "Master's Aircraft Toolbox   (Bound) ×100",
      "Gold Chest (Bound) ×5000",
      "Metal Fragment ×20000",
      "MealBasket ×2500",
      "Morion (Bound) ×40000",
      "[UC] Crafting Material   Selection Chest (Bound) ×800",
      "[C] Crafting Material x40   Selection Chest (Bound) ×1200",
      "[R] Arcane Scroll Selection   Chest (Bound) ×400",
      "Time Recharger - Masarta   Special Dungeon ×400",
      "Time Charging Device -   Harphenon Sanctum ×200",
      "Elemental Extraction of   Fusion 11 times (attribution) ×1000",
      "Brilliant Weapon Refinement   Stone (Bound) ×200",
      "Brilliant Armor Refinement   Stone (Bound) ×200",
      "Brilliant Accessory   Refinement Stone (Bound) ×200",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×100",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×100",
      "+8 Knight Jewel (Bound) ×1",
      "+8 Fighter Jewel (Bound) ×1",
      "+8 Philosopher's Jewel   (Bound) ×1",
      "+8 Incense Burner of Vitality   (Bound) ×1",
      "+8 Incense Burner of   Mentality (Bound) ×1",
      "+8 Incense Burner of   Endurance (Bound) ×1",
      "crusade Loot Chest   (Attributed) ×20",
      "Gilded Monarch Raven (Bound) ×1",
    ],
  },
  {
    amount: 3500,
    rewards: [
      "Mileage ×250000",
      "Seal of Advancement (Bound) ×62500",
      "Higher Seal of Advancement   (Bound) ×3125",
      "Nightcrows Stimulant of   Growth (BOUND) ×6250",
      "Eligio Stimulant of EXP   (Bound) ×2500",
      "Artisan Aircraft Toolbox   (Bound) ×500",
      "Gold Chest (Bound) ×6250",
      "Metal Fragment ×50000",
      "MealBasket ×3125",
      "Morion (Bound) ×50000",
      "[UC] Crafting Material   Selection Chest (Bound) ×1000",
      "[C] Crafting Material x40   Selection Chest (Bound) ×1500",
      "[R] Arcane Scroll Selection   Chest (Bound) ×500",
      "Time Recharger - Masarta   Special Dungeon ×500",
      "Time Charging Device -   Harphenon Sanctum ×250",
      "Elemental Extraction of   Fusion 11 times (attribution) ×1250",
      "Shining Weapon Enhancement   Chest (Bound) ×1000",
      "Shining Armor Enhancement   Chest ×1000",
      "Shining Accessory Enhancement   Chest (Bound) ×1000",
      "Brilliant Weapon Refinement   Stone (Bound) ×200",
      "Brilliant Armor Refinement   Stone (Bound) ×200",
      "Brilliant Accessory   Refinement Stone (Bound) ×200",
      "+8 Hourglass of Desert   (Bound) (Bound)",
      "+8 Hourglass of Ice and Snow   (Bound) (Bound)",
      "+8 Hourglass of Verdure   (Bound) (Bound)",
      "+8 Die of Scorching Heat   (Bound) ×1",
      "+8 Die of Oceans (Bound) ×1",
      "+8 Die of Thunderbolts   (Bound) ×1",
      "Guardian's   Scepter(Attribution) ×10000",
    ],
  },
  {
    amount: 4000,
    rewards: [
      "Mileage ×300000",
      "Seal of Advancement (Bound) ×75000",
      "Higher Seal of Advancement   (Bound) ×3750",
      "Artisan Aircraft Toolbox   (Bound) ×600",
      "Master's Aircraft Toolbox   (Bound) ×200",
      "Gold Chest (Bound) ×7500",
      "Metal Fragment ×30000",
      "MealBasket ×3750",
      "Morion (Bound) ×60000",
      "[UC] Crafting Material   Selection Chest (Bound) ×1200",
      "[C] Crafting Material x40   Selection Chest (Bound) ×1800",
      "[R] Arcane Scroll Selection   Chest (Bound) ×600",
      "Time Recharger - Masarta   Special Dungeon ×600",
      "Time Charging Device -   Harphenon Sanctum ×300",
      "Elemental Extraction of   Fusion 11 times (attribution) ×1500",
      "Brilliant Weapon Refinement   Stone (Bound) ×200",
      "Brilliant Armor Refinement   Stone (Bound) ×200",
      "Brilliant Accessory   Refinement Stone (Bound) ×200",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×100",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×100",
      "+9 Knight Jewel (Bound) ×1",
      "+9 Fighter Jewel (Bound) ×1",
      "+9 Philosopher's Jewel   (Bound) ×1",
      "+9 Incense Burner of Vitality   (Bound) ×1",
      "+9 Incense Burner of   Mentality (Bound) ×1",
      "+9 Incense Burner of   Endurance (Bound) ×1",
      "for gray-scaled babies   (Bound) ×1",
    ],
  },
  {
    amount: 4500,
    rewards: [
      "Mileage ×350000",
      "Seal of Advancement (Bound) ×87500",
      "Higher Seal of Advancement   (Bound) ×4375",
      "Nightcrows Stimulant of   Growth (BOUND) ×8750",
      "Eligio Stimulant of EXP   (Bound) ×3500",
      "Artisan Aircraft Toolbox   (Bound) ×700",
      "Gold Chest (Bound) ×8750",
      "Metal Fragment ×35000",
      "MealBasket ×4375",
      "Morion (Bound) ×70000",
      "[UC] Crafting Material   Selection Chest (Bound) ×1400",
      "[C] Crafting Material x40   Selection Chest (Bound) ×2100",
      "[R] Arcane Scroll Selection   Chest (Bound) ×700",
      "Time Recharger - Masarta   Special Dungeon ×700",
      "Time Charging Device -   Harphenon Sanctum ×350",
      "Elemental Extraction of   Fusion 11 times (attribution) ×1750",
      "Shining Weapon Enhancement   Chest (Bound) ×1000",
      "Shining Armor Enhancement   Chest ×1000",
      "Shining Accessory Enhancement   Chest (Bound) ×1000",
      "Brilliant Weapon Refinement   Stone (Bound) ×200",
      "Brilliant Armor Refinement   Stone (Bound) ×200",
      "Brilliant Accessory   Refinement Stone (Bound) ×200",
      "+9 Hourglass of Desert   (Bound)",
      "+9 Hourglass of Ice and Snow   (Bound)",
      "+9 Hourglass of Verdure   (Bound)",
      "+9 Die of Scorching Heat   (Bound) ×1",
      "+9 Die of Oceans (Bound) ×1",
      "+9 Die of Thunderbolts   (Bound) ×1",
      "Glorius Albatross Wings   (Bound) ×1",
    ],
  },
  {
    amount: 5000,
    rewards: [
      "Diamond ×2000000",
      "Mileage ×400000",
      "Seal of Advancement (Bound) ×100000",
      "Higher Seal of Advancement   (Bound) ×5000",
      "Artisan Aircraft Toolbox   (Bound) ×800",
      "Master's Aircraft Toolbox   (Bound) ×400",
      "Gold Chest (Bound) ×10000",
      "Metal Fragment ×40000",
      "MealBasket ×5000",
      "Morion (Bound) ×80000",
      "[UC] Crafting Material   Selection Chest (Bound) ×1600",
      "[C] Crafting Material x40   Selection Chest (Bound) ×2400",
      "[R] Arcane Scroll Selection   Chest (Bound) ×800",
      "Time Recharger - Masarta   Special Dungeon ×800",
      "Time Charging Device -   Harphenon Sanctum ×400",
      "Elemental Extraction of   Fusion 11 times (attribution) ×2000",
      "Brilliant Weapon Refinement   Stone (Bound) ×2500",
      "Brilliant Armor Refinement   Stone (Bound) ×2500",
      "Brilliant Accessory   Refinement Stone (Bound) ×2500",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×500",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×500",
      "+9 Knight Jewel (Bound) ×1",
      "+9 Fighter Jewel (Bound) ×1",
      "+9 Philosopher's Jewel   (Bound) ×1",
      "+9 Incense Burner of Vitality   (Bound) ×1",
      "+9 Incense Burner of   Mentality (Bound) ×1",
      "+9 Incense Burner of   Endurance (Bound) ×1",
    ],
  },
  {
    amount: 6000,
    rewards: [
      "Mileage ×500000",
      "Seal of Advancement (Bound) ×250000",
      "Higher Seal of Advancement   (Bound) ×12500",
      "Artisan Aircraft Toolbox   (Bound) ×1000",
      "Master's Aircraft Toolbox   (Bound) ×500",
      "Gold Chest (Bound) ×12500",
      "Metal Fragment ×50000",
      "MealBasket ×6250",
      "Morion (Bound) ×100000",
      "[UC] Crafting Material   Selection Chest (Bound) ×2000",
      "[C] Crafting Material x40   Selection Chest (Bound) ×3000",
      "[R] Arcane Scroll Selection   Chest (Bound) ×1000",
      "Time Recharger - Masarta   Special Dungeon ×1000",
      "Time Charging Device -   Harphenon Sanctum ×500",
      "Elemental Extraction of   Fusion 11 times (attribution) ×2500",
      "Shining Weapon Enhancement   Chest (Bound) ×6000",
      "Shining Armor Enhancement   Chest ×6000",
      "Shining Accessory Enhancement   Chest (Bound) ×6000",
      "Brilliant Weapon Refinement   Stone (Bound) ×3000",
      "Brilliant Armor Refinement   Stone (Bound) ×3000",
      "Brilliant Accessory   Refinement Stone (Bound) ×3000",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×600",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×600",
      "+10 Knight Jewel (Bound) ×1",
      "+10 Fighter Jewel (Bound) ×1",
      "+10 Philosopher's Jewel   (Bound) ×1",
      "+10 Incense Burner of   Vitality (Bound) ×1",
      "+10 Incense Burner of   Mentality (Bound) ×1",
      "+10 Incense Burner of   Endurance (Bound) ×1",
    ],
  },
  {
    amount: 7000,
    rewards: [
      "Mileage ×550000",
      "Seal of Advancement (Bound) ×275000",
      "Higher Seal of Advancement   (Bound) ×13750",
      "Master's Aircraft Toolbox   (Bound) ×1000",
      "Gold Chest (Bound) ×13750",
      "Metal Fragment ×60000",
      "MealBasket ×6875",
      "Morion (Bound) ×110000",
      "[UC] Crafting Material   Selection Chest (Bound) ×2200",
      "[C] Crafting Material x40   Selection Chest (Bound) ×3300",
      "[R] Arcane Scroll Selection   Chest (Bound) ×1100",
      "Time Recharger - Masarta   Special Dungeon ×1100",
      "Time Charging Device -   Harphenon Sanctum ×550",
      "Elemental Extraction of   Fusion 11 times (attribution) ×2750",
      "Shining Weapon Enhancement   Chest (Bound) ×7000",
      "Shining Armor Enhancement   Chest ×7000",
      "Shining Accessory Enhancement   Chest (Bound) ×7000",
      "Brilliant Weapon Refinement   Stone (Bound) ×3500",
      "Brilliant Armor Refinement   Stone (Bound) ×3500",
      "Brilliant Accessory   Refinement Stone (Bound) ×3500",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×700",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×700",
      "+10 Knight Jewel (Bound) ×1",
      "+10 Fighter Jewel (Bound) ×1",
      "+10 Philosopher's Jewel   (Bound) ×1",
      "+10 Incense Burner of   Vitality (Bound) ×1",
      "+10 Incense Burner of   Mentality (Bound) ×1",
      "+10 Incense Burner of   Endurance (Bound) ×1",
      "crusade Loot Chest   (Attributed) ×100",
      "Tiaraka of Flushing (Bound) ×1",
    ],
  },
  {
    amount: 8000,
    rewards: [
      "Mileage ×700000",
      "Seal of Advancement (Bound) ×350000",
      "Higher Seal of Advancement   (Bound) ×17500",
      "Master's Aircraft Toolbox   (Bound) ×1500",
      "Gold Chest (Bound) ×17500",
      "Metal Fragment ×70000",
      "MealBasket ×8750",
      "Morion (Bound) ×140000",
      "[UC] Crafting Material   Selection Chest (Bound) ×2800",
      "[C] Crafting Material x40   Selection Chest (Bound) ×4200",
      "[R] Arcane Scroll Selection   Chest (Bound) ×1400",
      "Time Recharger - Masarta   Special Dungeon ×1400",
      "Time Charging Device -   Harphenon Sanctum ×700",
      "Elemental Extraction of   Fusion 11 times (attribution) ×3500",
      "Shining Weapon Enhancement   Chest (Bound) ×8000",
      "Shining Armor Enhancement   Chest ×8000",
      "Shining Accessory Enhancement   Chest (Bound) ×8000",
      "Brilliant Weapon Refinement   Stone (Bound) ×4000",
      "Brilliant Armor Refinement   Stone (Bound) ×4000",
      "Brilliant Accessory   Refinement Stone (Bound) ×4000",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×800",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×800",
      "+11 Knight Jewel (Bound) ×1",
      "+11 Fighter Jewel (Bound) ×1",
      "+11 Philosopher's Jewel   (Bound) ×1",
      "+11 Incense Burner of   Vitality (Bound) ×1",
      "+11 Incense Burner of   Mentality (Bound) ×1",
      "+11 Incense Burner of   Endurance (Bound) ×1",
    ],
  },
  {
    amount: 9000,
    rewards: [
      "Mileage ×800000",
      "Artisan Aircraft Toolbox   (Bound) ×1600",
      "Gold Chest (Bound) ×20000",
      "Metal Fragment ×80000",
      "MealBasket ×10000",
      "Morion (Bound) ×160000",
      "[UC] Crafting Material   Selection Chest (Bound) ×3200",
      "[C] Crafting Material x40   Selection Chest (Bound) ×4800",
      "[R] Arcane Scroll Selection   Chest (Bound) ×1600",
      "Time Recharger - Masarta   Special Dungeon ×1600",
      "Time Charging Device -   Harphenon Sanctum ×800",
      "Elemental Extraction of   Fusion 11 times (attribution) ×4000",
      "Shining Weapon Enhancement   Chest (Bound) ×9000",
      "Shining Armor Enhancement   Chest ×9000",
      "Shining Accessory Enhancement   Chest (Bound) ×9000",
      "Brilliant Weapon Refinement   Stone (Bound) ×4500",
      "Brilliant Armor Refinement   Stone (Bound) ×4500",
      "Brilliant Accessory   Refinement Stone (Bound) ×4500",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×900",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×900",
      "+11 Knight Jewel (Bound) ×1",
      "+11 Fighter Jewel (Bound) ×1",
      "+11 Philosopher's Jewel   (Bound) ×1",
      "+11 Incense Burner of   Vitality (Bound) ×1",
      "+11 Incense Burner of   Mentality (Bound) ×1",
      "+11 Incense Burner of   Endurance (Bound) ×1",
      "Guardian's   Scepter(Attribution) 150000",
    ],
  },
  {
    amount: 10000,
    rewards: [
      "Diamond ×5000000",
      "Mileage ×1000000",
      "Master's Aircraft Toolbox   (Bound) ×4000",
      "Gold Chest (Bound) ×25000",
      "Metal Fragment ×100000",
      "MealBasket ×12500",
      "Morion (Bound) ×200000",
      "[UC] Crafting Material   Selection Chest (Bound) ×4000",
      "[C] Crafting Material x40   Selection Chest (Bound) ×6000",
      "[R] Arcane Scroll Selection   Chest (Bound) ×2000",
      "Time Recharger - Masarta   Special Dungeon ×2000",
      "Time Charging Device -   Harphenon Sanctum ×1000",
      "Elemental Extraction of   Fusion 11 times (attribution) ×5000",
      "Shining Weapon Enhancement   Chest (Bound) ×10000",
      "Shining Armor Enhancement   Chest ×10000",
      "Shining Accessory Enhancement   Chest (Bound) ×10000",
      "Brilliant Weapon Refinement   Stone (Bound) ×5000",
      "Brilliant Armor Refinement   Stone (Bound) ×5000",
      "Brilliant Accessory   Refinement Stone (Bound) ×5000",
      "Brilliant Enhancement Scroll   Selection Chest (Bound) ×1000",
      "Pitch-black Enhancement   Scroll Selection Chest (Bound) ×1000",
      "+12 Knight Jewel (Bound) ×1",
      "+12 Fighter Jewel (Bound) ×1",
      "+12 Philosopher's Jewel   (Bound) ×1",
      "+12 Incense Burner of   Vitality (Bound) ×1",
      "+12 Incense Burner of   Mentality (Bound) ×1",
      "+12 Incense Burner of   Endurance (Bound) ×1",
      "+12 Hourglass of Desert   (Bound)",
      "+12 Hourglass of Ice and Snow   (Bound)",
      "+12 Hourglass of Verdure   (Bound)",
      "+12 Die of Scorching Heat   (Bound) ×1",
      "+12 Die of Oceans (Bound) ×1",
      "+12 Die of Thunderbolts   (Bound) ×1",
      "Guardian's   Scepter(Attribution) 250000",
      "crusade Loot Chest   (Attributed) ×400",
      "golden Necklace Insignia (Attributed) x4",
      "golden Ring Insignia (Attributed) x8",
    ],
  },
  {
    amount: 11000,
    rewards: [
      "Frozen Tear (Bound) ×5000",
      "Morion (Bound) ×300000",
      "[UC] Crafting Material Selection Chest (Bound) ×4000",
      "[C] Crafting Material x40 Selection Chest (Bound) ×6000",
      "[R] Arcane Scroll Selection Chest (Bound) ×3000",
      "Time Recharger - Masarta Special Dungeon ×2000",
      "crusade Loot Chest (Attributed) ×400",
      "golden Necklace Insignia (Attributed) ×8",
    ],
  },
  {
    amount: 12000,
    rewards: [
      "Metal Fragment ×300000",
      "Morion (Bound) ×300000",
      "Shining Weapon Enhancement Scroll Chest (Bound) ×10000",
      "Shining Armor Enhancement Scroll Chest ×10000",
      "Shining Accessory Enhancement Scroll Chest (Bound) ×10000",
      "Time Charging Device - Harphenon Sanctum ×1000",
      "Guardian's Scepter (Attribution) ×300000",
      "golden Ring Insignia (Attributed) ×16",
    ],
  },
  {
    amount: 13000,
    rewards: [
      "Frozen Tear (Bound) ×10000",
      "Morion (Bound) ×300000",
      "[UC] Crafting Material Selection Chest (Bound) ×4000",
      "[C] Crafting Material x40 Selection Chest (Bound) ×6000",
      "[R] Arcane Scroll Selection Chest (Bound) ×3000",
      "Time Recharger - Masarta Special Dungeon ×2000",
      "crusade Loot Chest (Attributed) ×400",
      "golden Necklace Insignia (Attributed) ×12",
    ],
  },
  {
    amount: 14000,
    rewards: [
      "Metal Fragment ×300000",
      "Morion (Bound) ×300000",
      "Shining Weapon Enhancement Scroll Chest (Bound) ×10000",
      "Shining Armor Enhancement Scroll Chest ×10000",
      "Shining Accessory Enhancement Scroll Chest (Bound) ×10000",
      "Time Charging Device - Harphenon Sanctum ×1000",
      "crusade Loot Chest (Attributed) ×400",
      "golden Ring Insignia (Attributed) ×20",
    ],
  },
  {
    amount: 15000,
    rewards: [
      "Diamonds ×5000000",
      "Frozen Tear (Bound) ×20000",
      "Morion (Bound) ×300000",
      "[UC] Crafting Material Selection Chest (Bound) ×8000",
      "[C] Crafting Material x40 Selection Chest (Bound) ×15000",
      "[R] Arcane Scroll Selection Chest (Bound) ×10000",
      "Guardian's Scepter (Attribution) ×350000",
      "crusade Loot Chest (Attributed) ×400",
      "golden Necklace Insignia (Attributed) ×20",
      "golden Ring Insignia (Attributed) ×40",
      "Lionheart's Sacred Insignia (Bound) ×1",
    ],
  },
  {
    amount: 18000,
    rewards: [
      "Frozen Tear (Bound) ×20000",
      "Morion (Bound) ×300000",
      "[UC] Crafting Material Selection Chest (Bound) ×8000",
      "[C] Crafting Material x40 Selection Chest (Bound) ×15000",
      "[R] Arcane Scroll Selection Chest (Bound) ×10000",
      "Guardian's Scepter (Attribution) ×350000",
      "crusade Loot Chest (Attributed) ×400",
      "golden Necklace Insignia (Attributed) ×20",
      "golden Ring Insignia (Attributed) ×40",
      "Lionheart's Sacred Insignia (Bound) ×1",
    ],
  },
  {
    amount: 20000,
    rewards: [
      "Diamonds ×8000000",
      "Gaspar’s Savage Greatsword (Bound) ×5",
      "Theophil’s Creed Spear (Bound) ×5",
      "Ludwig’s Straight Sword of Justice (Bound) ×5",
      "Brandt’s Domination Twin Sword (Bound) ×5",
      "Clemen’s Freedom Dagger (Bound) ×5",
      "Alyn’s Illusion Longbow (Bound) ×5",
      "Ruling Segum of Zenesia (Bound) ×5",
      "Johannes' Motive Scepter (Bound) ×5",
      "Eleanor’s Ambition Staff (Bound) ×5",
      "Guardian's Scepter (Attribution) ×350000",
      "crusade Loot Chest (Attributed) ×400",
    ],
  }
]