-- PlayCrows Event Center v7 - Link security and duplicate detection
-- Run AFTER the v1-v5 Event Center migrations.
-- This migration is additive: it does not delete/reset submissions or change their statuses.

-- Normalize URLs enough to catch common copy/paste variants such as:
-- http vs https, www vs non-www, URL fragments, and trailing slashes.
create or replace function public.normalize_event_claim_url(p_url text)
returns text
language plpgsql
immutable
as $$
declare
  v text;
  v_host text;
  v_rest text;
begin
  v := btrim(coalesce(p_url, ''));
  if v = '' or v !~* '^https?://[^[:space:]]+$' then
    return null;
  end if;

  -- Browser fragments never change the server resource.
  v := regexp_replace(v, '#.*$', '');
  -- Protocol differences should not make the same proof look unique.
  v := regexp_replace(v, '^https?://', '', 'i');

  -- Split and normalize only the hostname. Keep path/query casing intact because
  -- paths on some websites can be case-sensitive.
  v_host := substring(v from '^([^/?]+)');
  if v_host is null then
    return null;
  end if;
  v_rest := substring(v from length(v_host) + 1);
  v_host := lower(v_host);
  v_host := regexp_replace(v_host, '^www\.', '', 'i');

  -- Common Facebook host aliases point to the same content.
  if v_host in ('m.facebook.com', 'web.facebook.com') then
    v_host := 'facebook.com';
  end if;

  v := v_host || coalesce(v_rest, '');
  -- Remove only trailing slashes; do not strip query parameters because some
  -- advertising/community sites identify posts through query IDs.
  v := regexp_replace(v, '/+$', '');
  return nullif(v, '');
end;
$$;

create or replace function public.extract_event_claim_urls(p_answers jsonb)
returns table(field_id text, raw_url text, normalized_url text)
language sql
immutable
as $$
  with fields as (
    select e.key as field_id, e.value
    from jsonb_each(coalesce(p_answers, '{}'::jsonb)) e
  ), values_expanded as (
    select f.field_id,
           case
             when jsonb_typeof(f.value) = 'string' then f.value #>> '{}'
             else null
           end as raw_url
    from fields f
    where jsonb_typeof(f.value) = 'string'

    union all

    select f.field_id, a.value #>> '{}' as raw_url
    from fields f
    cross join lateral jsonb_array_elements(case when jsonb_typeof(f.value) = 'array' then f.value else '[]'::jsonb end) a(value)
    where jsonb_typeof(f.value) = 'array'
      and jsonb_typeof(a.value) = 'string'
  )
  select v.field_id,
         btrim(v.raw_url),
         public.normalize_event_claim_url(v.raw_url)
  from values_expanded v
  where btrim(coalesce(v.raw_url, '')) ~* '^https?://[^[:space:]]+$'
    and public.normalize_event_claim_url(v.raw_url) is not null;
$$;

create table if not exists public.event_submission_links (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.event_submissions(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  field_id text not null,
  raw_url text not null,
  normalized_url text not null,
  created_at timestamptz not null default now(),
  unique (submission_id, normalized_url)
);

create index if not exists event_submission_links_event_normalized_idx
  on public.event_submission_links(event_id, normalized_url);
create index if not exists event_submission_links_submission_idx
  on public.event_submission_links(submission_id);

alter table public.event_submission_links enable row level security;
grant select on table public.event_submission_links to authenticated;

drop policy if exists "Admins read event submission links" on public.event_submission_links;
create policy "Admins read event submission links"
on public.event_submission_links
for select to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Keep the normalized-link index in sync with each submission.
create or replace function public.sync_event_submission_links()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.event_submission_links where submission_id = new.id;

  insert into public.event_submission_links(submission_id, event_id, field_id, raw_url, normalized_url)
  select new.id, new.event_id, x.field_id, x.raw_url, x.normalized_url
  from public.extract_event_claim_urls(new.answers) x
  on conflict (submission_id, normalized_url) do nothing;

  return new;
end;
$$;

-- Protect at the database layer. This cannot be bypassed by editing the browser UI.
-- 1) A claim cannot submit the same normalized URL twice.
-- 2) A player cannot submit a URL already used in an APPROVED claim by another player.
-- 3) Two pending claims may temporarily contain the same URL so a malicious first submitter
--    cannot lock the legitimate owner out; the admin dashboard will flag the conflict.
--    When one is approved, the other cannot also be approved with that same proof URL.
create or replace function public.guard_event_submission_links()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer;
  v_unique integer;
  v_has_approved_conflict boolean;
begin
  select count(*), count(distinct normalized_url)
    into v_total, v_unique
  from public.extract_event_claim_urls(new.answers);

  if v_total <> v_unique then
    raise exception 'Duplicate links detected in this claim. Please submit each proof link only once.';
  end if;

  -- Block reuse of an approved proof by a different player on the same event.
  -- This check also runs when an admin changes a pending claim to approved.
  if tg_op = 'INSERT' or new.status = 'approved' then
    select exists (
      select 1
      from public.extract_event_claim_urls(new.answers) incoming
      join public.event_submission_links l
        on l.event_id = new.event_id
       and l.normalized_url = incoming.normalized_url
      join public.event_submissions prior on prior.id = l.submission_id
      where prior.id <> new.id
        and prior.status = 'approved'
        and not (
          lower(regexp_replace(trim(prior.discord_username), '[[:space:]]+', '', 'g')) =
            lower(regexp_replace(trim(new.discord_username), '[[:space:]]+', '', 'g'))
          or (
            nullif(lower(regexp_replace(trim(coalesce(prior.player_id, '')), '[[:space:]]+', '', 'g')), '') is not null
            and nullif(lower(regexp_replace(trim(coalesce(new.player_id, '')), '[[:space:]]+', '', 'g')), '') =
                nullif(lower(regexp_replace(trim(coalesce(prior.player_id, '')), '[[:space:]]+', '', 'g')), '')
          )
          or (
            nullif(lower(regexp_replace(trim(coalesce(prior.character_name, '')), '[[:space:]]+', '', 'g')), '') is not null
            and nullif(lower(regexp_replace(trim(coalesce(new.character_name, '')), '[[:space:]]+', '', 'g')), '') =
                nullif(lower(regexp_replace(trim(coalesce(prior.character_name, '')), '[[:space:]]+', '', 'g')), '')
          )
        )
    ) into v_has_approved_conflict;

    if v_has_approved_conflict then
      raise exception 'One or more submitted links have already been used in an approved claim for this event.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists event_submission_links_guard on public.event_submissions;
create trigger event_submission_links_guard
before insert or update of answers, event_id, discord_username, character_name, player_id, status
on public.event_submissions
for each row execute function public.guard_event_submission_links();

drop trigger if exists event_submission_links_sync on public.event_submissions;
create trigger event_submission_links_sync
after insert or update of answers, event_id
on public.event_submissions
for each row execute function public.sync_event_submission_links();

-- Backfill every existing claim so the admin dashboard can immediately detect historical reuse.
insert into public.event_submission_links(submission_id, event_id, field_id, raw_url, normalized_url)
select s.id, s.event_id, x.field_id, x.raw_url, x.normalized_url
from public.event_submissions s
cross join lateral public.extract_event_claim_urls(s.answers) x
on conflict (submission_id, normalized_url) do nothing;

comment on table public.event_submission_links is
  'Normalized proof URLs extracted from event submissions for duplicate/reuse detection.';
